name: CI
on:
  push:
  pull_request:
env:
  VulkanSDKVersion: 1.2.162.1
jobs:
  linux-build:
    runs-on: ubuntu-latest
    env:
      BuildDocEnabled: ${{github.event_name == 'push' && github.ref == 'refs/heads/master'}}
      VULKAN_SDK: $GITHUB_WORKSPACE/../$VulkanSDKVersion/x86_64
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: Vulkan Install
      uses: humbletim/setup-vulkan-sdk@v1.0.3
    - name: VSG Checkout
      uses: actions/checkout@v2
      with:
        repository: vsg-dev/VulkanSceneGraph
        path: vsg
    - name: VSG Build and Install
      run: |
        cd vsg
        cmake -D Vulkan_INCLUDE_DIR="${{env.VULKAN_SDK}}/include" \
          -D Vulkan_LIBRARY="${{env.VULKAN_SDK}}/lib/libvulkan.so" .
        make -j 2
        sudo make install
    - name: vsgExamples Build and Install
      run: |
        cd main
        cmake -D Vulkan_INCLUDE_DIR="${{env.VULKAN_SDK}}/include" \
          -D Vulkan_LIBRARY="${{env.VULKAN_SDK}}/lib/libvulkan.so" .
        make -j 2
        sudo make install
        